Racecourse.delete_all

Racecourse.find_or_create_by_id(id: 1,  name: 'Aintree')
Racecourse.find_or_create_by_id(id: 2,  name: 'Ascot')
Racecourse.find_or_create_by_id(id: 3,  name: 'Ayr')
Racecourse.find_or_create_by_id(id: 4,  name: 'Cheltenham')
Racecourse.find_or_create_by_id(id: 5,  name: 'Chepstow')
Racecourse.find_or_create_by_id(id: 6,  name: 'Chester')
Racecourse.find_or_create_by_id(id: 7,  name: 'Doncaster')
Racecourse.find_or_create_by_id(id: 8,  name: 'Goodwood')
Racecourse.find_or_create_by_id(id: 9,  name: 'Haydock')
Racecourse.find_or_create_by_id(id: 10, name: 'Kempton')
Racecourse.find_or_create_by_id(id: 11, name: 'Lingfield')
Racecourse.find_or_create_by_id(id: 12, name: 'Newbury')
Racecourse.find_or_create_by_id(id: 13, name: 'Newcastle')
Racecourse.find_or_create_by_id(id: 14, name: 'Newmarket')
Racecourse.find_or_create_by_id(id: 15, name: 'Sandown')
Racecourse.find_or_create_by_id(id: 16, name: 'York')
