defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 15432
  pool: 5

development:
  database: rocket_horse_development
  username: developer
  password: password
  <<: *defaults

test: &test
  database: rocket_horse_test
  username: developer
  password: password
  <<: *defaults

production:
  database: rocket_horse_production
  username: developer
  password: password
  port: 5432
  <<: *defaults
